export const GET_PROPERTY_LOCATIONS = 'app/FixAndFlip/GET_PROPERTY_LOCATIONS';
export const GET_PROPERTY_LOCATIONS_SUCCESS =
  'app/FixAndFlip/GET_PROPERTY_LOCATIONS_SUCCESS';
export const SET_PROPERTY_LOCATION = 'app/FixAndFlip/SET_PROPERTY_LOCATION';

export const GET_PROPERTY_TYPES = 'app/FixAndFlip/GET_PROPERTY_TYPES';
export const GET_PROPERTY_TYPES_SUCCESS =
  'app/FixAndFlip/GET_PROPERTY_TYPES_SUCCESS';

export const GET_PROPERTY_TYPOLOGIES = 'app/FixAndFlip/GET_PROPERTY_TYPOLOGIES';
export const GET_PROPERTY_TYPOLOGIES_SUCCESS =
  'app/FixAndFlip/GET_PROPERTY_TYPOLOGIES_SUCCESS';

export const GET_PROPERTY_CONDITIONS = 'app/FixAndFlip/GET_PROPERTY_CONDITIONS';
export const GET_PROPERTY_CONDITIONS_SUCCESS =
  'app/FixAndFlip/GET_PROPERTY_CONDITIONS_SUCCESS';

export const GET_ACQUISITION_TYPES = 'app/FixAndFlip/GET_ACQUISITION_TYPES';
export const GET_ACQUISITION_TYPES_SUCCESS =
  'app/FixAndFlip/GET_ACQUISITION_TYPES_SUCCESS';

export const GET_IRS_CATEGORIES = 'app/FixAndFlip/GET_IRS_CATEGORIES';
export const GET_IRS_CATEGORIES_SUCCESS =
  'app/FixAndFlip/GET_IRS_CATEGORIES_SUCCESS';

export const GET_IRS_DEPENDENTS_LIST = 'app/FixAndFlip/GET_IRS_DEPENDENTS_LIST';
export const GET_IRS_DEPENDENTS_LIST_SUCCESS =
  'app/FixAndFlip/GET_IRS_DEPENDENTS_LIST_SUCCESS';

export const GET_IRS_CATEGORY_REGIONS =
  'app/FixAndFlip/GET_IRS_CATEGORY_REGIONS';
export const GET_IRS_CATEGORY_REGIONS_SUCCESS =
  'app/FixAndFlip/GET_IRS_CATEGORY_REGIONS_SUCCESS';

export const GET_PERCENTILES = 'app/FixAndFlip/GET_PERCENTILES';
export const GET_PERCENTILES_SUCCESS = 'app/FixAndFlip/GET_PERCENTILES_SUCCESS';

export const SET_INPUT_VALUE = 'app/FixAndFlip/SET_INPUT_VALUE';
export const SET_INPUT_ERROR = 'app/FixAndFlip/SET_INPUT_ERROR';

export const SET_ANALYZE_BUTTON_DISABLED =
  'app/FixAndFlip/SET_ANALYZE_BUTTON_DISABLED';

export const GET_ANALYSIS = 'app/FixAndFlip/GET_ANALYSIS';
export const GET_ANALYSIS_SUCCESS = 'app/FixAndFlip/GET_ANALYSIS_SUCCESS';
export const GET_ANALYSIS_ERROR = 'app/FixAndFlip/GET_ANALYSIS_ERROR';
