export const GET_MAP_PROPERTIES = 'app/Map/GET_MAP_PROPERTIES';
export const GET_MAP_PROPERTIES_SUCCESS = 'app/Map/GET_MAP_PROPERTIES_SUCCESS';
export const GET_MAP_PROPERTIES_ERROR = 'app/Map/GET_MAP_PROPERTIES_ERROR';

export const GET_LOCATION_BOUNDARIES = 'app/Map/GET_LOCATION_BOUNDARIES';
export const GET_LOCATION_BOUNDARIES_SUCCESS =
  'app/Map/GET_LOCATION_BOUNDARIES_SUCCESS';
export const GET_LOCATION_BOUNDARIES_ERROR =
  'app/Map/GET_LOCATION_BOUNDARIES_ERROR';

export const SET_MAP_FILTER = 'app/Map/SET_MAP_FILTER';
export const SET_CENTER = 'app/Map/SET_CENTER';
export const START_ANIMATE_MARKER = 'app/Map/START_ANIMATE_MARKER';
export const STOP_ANIMATE_MARKER = 'app/Map/STOP_ANIMATE_MARKER';
