export const GET_PROPERTY_LOCATIONS = 'app/Investments/GET_PROPERTY_LOCATIONS';
export const GET_PROPERTY_LOCATIONS_SUCCESS =
  'app/Investments/GET_PROPERTY_LOCATIONS_SUCCESS';
export const SET_PROPERTY_LOCATION = 'app/Investments/SET_PROPERTY_LOCATION';

export const GET_PROPERTY_TYPES = 'app/Investments/GET_PROPERTY_TYPES';
export const GET_PROPERTY_TYPES_SUCCESS =
  'app/Investments/GET_PROPERTY_TYPES_SUCCESS';

export const GET_PROPERTY_TYPOLOGIES =
  'app/Investments/GET_PROPERTY_TYPOLOGIES';
export const GET_PROPERTY_TYPOLOGIES_SUCCESS =
  'app/Investments/GET_PROPERTY_TYPOLOGIES_SUCCESS';

export const GET_PROPERTY_CONDITIONS =
  'app/Investments/GET_PROPERTY_CONDITIONS';
export const GET_PROPERTY_CONDITIONS_SUCCESS =
  'app/Investments/GET_PROPERTY_CONDITIONS_SUCCESS';

export const GET_ACQUISITION_TYPES = 'app/Investments/GET_ACQUISITION_TYPES';
export const GET_ACQUISITION_TYPES_SUCCESS =
  'app/Investments/GET_ACQUISITION_TYPES_SUCCESS';

export const GET_IRS_CATEGORIES = 'app/Investments/GET_IRS_CATEGORIES';
export const GET_IRS_CATEGORIES_SUCCESS =
  'app/Investments/GET_IRS_CATEGORIES_SUCCESS';

export const GET_IRS_DEPENDENTS_LIST =
  'app/Investments/GET_IRS_DEPENDENTS_LIST';
export const GET_IRS_DEPENDENTS_LIST_SUCCESS =
  'app/Investments/GET_IRS_DEPENDENTS_LIST_SUCCESS';

export const GET_IRS_CATEGORY_REGIONS =
  'app/Investments/GET_IRS_CATEGORY_REGIONS';
export const GET_IRS_CATEGORY_REGIONS_SUCCESS =
  'app/Investments/GET_IRS_CATEGORY_REGIONS_SUCCESS';

export const GET_CI_PERCENTILES = 'app/Investments/GET_CI_PERCENTILES';
export const GET_CI_PERCENTILES_SUCCESS =
  'app/Investments/GET_CI_PERCENTILES_SUCCESS';

export const SET_INPUT_VALUE = 'app/Investments/SET_INPUT_VALUE';
export const SET_INPUT_ERROR = 'app/Investments/SET_INPUT_ERROR';

export const SET_ANALYZE_BUTTON_DISABLED =
  'app/Investments/SET_ANALYZE_BUTTON_DISABLED';

export const GET_ANALYSIS = 'app/Investments/GET_ANALYSIS';
export const GET_ANALYSIS_SUCCESS = 'app/Investments/GET_ANALYSIS_SUCCESS';
export const GET_ANALYSIS_ERROR = 'app/Investments/GET_ANALYSIS_ERROR';
