export const GET_ANALYSIS_DATA_BY_ID = 'app/Analysis/GET_ANALYSIS_DATA_BY_ID';
export const GET_ANALYSIS_DATA_SUCCESS_BY_ID =
  'app/Analysis/GET_ANALYSIS_DATA_SUCCESS_BY_ID';

export const GET_PROPERTY_LOCATIONS = 'app/Analysis/GET_PROPERTY_LOCATIONS';
export const GET_PROPERTY_LOCATIONS_SUCCESS =
  'app/Analysis/GET_PROPERTY_LOCATIONS_SUCCESS';
export const SET_PROPERTY_LOCATION = 'app/Analysis/SET_PROPERTY_LOCATION';

export const GET_PROPERTY_TYPES = 'app/Analysis/GET_PROPERTY_TYPES';
export const GET_PROPERTY_TYPES_SUCCESS =
  'app/Analysis/GET_PROPERTY_TYPES_SUCCESS';

export const GET_PROPERTY_TYPOLOGIES = 'app/Analysis/GET_PROPERTY_TYPOLOGIES';
export const GET_PROPERTY_TYPOLOGIES_SUCCESS =
  'app/Analysis/GET_PROPERTY_TYPOLOGIES_SUCCESS';

export const GET_PROPERTY_CONDITIONS = 'app/Analysis/GET_PROPERTY_CONDITIONS';
export const GET_PROPERTY_CONDITIONS_SUCCESS =
  'app/Analysis/GET_PROPERTY_CONDITIONS_SUCCESS';

export const GET_PROPERTY_STATUS = 'app/Analysis/GET_PROPERTY_STATUS';
export const GET_PROPERTY_STATUS_SUCCESS =
  'app/Investments/GET_PROPERTY_STATUS_SUCCESS';

export const GET_ACQUISITION_TYPES = 'app/Analysis/GET_ACQUISITION_TYPES';
export const GET_ACQUISITION_TYPES_SUCCESS =
  'app/Investments/GET_ACQUISITION_TYPES_SUCCESS';

export const GET_CI_PERCENTILES = 'app/Analysis/GET_CI_PERCENTILES';
export const GET_CI_PERCENTILES_SUCCESS =
  'app/Analysis/GET_CI_PERCENTILES_SUCCESS';
