export const GET_PROPERTY_LOCATIONS = 'app/Analysis/GET_PROPERTY_LOCATIONS';
export const GET_PROPERTY_LOCATIONS_SUCCESS =
  'app/Analysis/GET_PROPERTY_LOCATIONS_SUCCESS';
export const SET_PROPERTY_LOCATION = 'app/Analysis/SET_PROPERTY_LOCATION';

export const GET_PROPERTY_TYPES = 'app/Analysis/GET_PROPERTY_TYPES';
export const GET_PROPERTY_TYPES_SUCCESS =
  'app/Analysis/GET_PROPERTY_TYPES_SUCCESS';

export const GET_PROPERTY_TYPOLOGIES = 'app/Analysis/GET_PROPERTY_TYPOLOGIES';
export const GET_PROPERTY_TYPOLOGIES_SUCCESS =
  'app/Analysis/GET_PROPERTY_TYPOLOGIES_SUCCESS';

export const GET_PROPERTY_CONDITIONS = 'app/Analysis/GET_PROPERTY_CONDITIONS';
export const GET_PROPERTY_CONDITIONS_SUCCESS =
  'app/Analysis/GET_PROPERTY_CONDITIONS_SUCCESS';

export const GET_ACQUISITION_TYPES = 'app/Analysis/GET_ACQUISITION_TYPES';
export const GET_ACQUISITION_TYPES_SUCCESS =
  'app/Analysis/GET_ACQUISITION_TYPES_SUCCESS';

export const GET_IRS_CATEGORIES = 'app/Analysis/GET_IRS_CATEGORIES';
export const GET_IRS_CATEGORIES_SUCCESS =
  'app/Analysis/GET_IRS_CATEGORIES_SUCCESS';

export const GET_IRS_DEPENDENTS_LIST = 'app/Analysis/GET_IRS_DEPENDENTS_LIST';
export const GET_IRS_DEPENDENTS_LIST_SUCCESS =
  'app/Analysis/GET_IRS_DEPENDENTS_LIST_SUCCESS';

export const GET_IRS_CATEGORY_REGIONS = 'app/Analysis/GET_IRS_CATEGORY_REGIONS';
export const GET_IRS_CATEGORY_REGIONS_SUCCESS =
  'app/Analysis/GET_IRS_CATEGORY_REGIONS_SUCCESS';

export const GET_PERCENTILES = 'app/Analysis/GET_PERCENTILES';
export const GET_PERCENTILES_SUCCESS = 'app/Analysis/GET_PERCENTILES_SUCCESS';

export const SET_INPUT_VALUE = 'app/Analysis/SET_INPUT_VALUE';
export const SET_INPUT_ERROR = 'app/Analysis/SET_INPUT_ERROR';

export const SET_ANALYZE_BUTTON_DISABLED =
  'app/Analysis/SET_ANALYZE_BUTTON_DISABLED';

export const GET_ANALYSIS_BY_ID = 'app/Analysis/GET_ANALYSIS_BY_ID';
export const GET_ANALYSIS_BY_ID_SUCCESS =
  'app/Analysis/GET_ANALYSIS_BY_ID_SUCCESS';
export const GET_ANALYSIS_BY_ID_ERROR = 'app/Analysis/GET_ANALYSIS_BY_ID_ERROR';

export const GET_PROPERTY_ANALYSIS_BY_ID =
  'app/Analysis/GET_PROPERTY_ANALYSIS_BY_ID';
export const GET_PROPERTY_ANALYSIS_BY_ID_SUCCESS =
  'app/Analysis/GET_PROPERTY_ANALYSIS_BY_ID_SUCCESS';
export const GET_PROPERTY_ANALYSIS_BY_ID_ERROR =
  'app/Analysis/GET_PROPERTY_ANALYSIS_BY_ID_ERROR';

export const SET_NEW_PROPERTY_ANALYSIS_PAGE_READY_NULL =
  'app/Analysis/SET_NEW_PROPERTY_ANALYSIS_PAGE_READY_NULL';
