export const DEFAULT_ACTION = 'app/Analysis/DEFAULT_ACTION';
export const GET_ANALYSIS_DATA_BY_ID = 'app/Analysis/GET_ANALYSIS_DATA_BY_ID';
export const GET_ANALYSIS_DATA_SUCCESS_BY_ID =
  'app/Analysis/GET_ANALYSIS_DATA_SUCCESS_BY_ID';
